name: Build and deploy Next.js app to Azure Web App - tech0-gen-6-step4-studentwebapp-6

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: tech0-gen-6-step4-studentwebapp-6

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Next.js app
        run: |
          cd frontend
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd frontend
          zip -r ../release.zip .next package.json package-lock.json public next.config.mjs

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d release

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_517B7ED437114BB5BCB49752A9724DCA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E8AEB751F5945979DC45A9E70083149 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_60551CCD2D344AF1B1BD2F87072BE05C }}

      - name: 'Update Azure Web App settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "${{ env.NODE_VERSION }}"
              }
            ]

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: release

      - name: 'Check deployment status'
        run: |
          echo "Deployment status: ${{ steps.deploy-to-webapp.outputs.status }}"
          echo "Deployment output: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
